[tool.black]
target-version = ['py310']
line-length = 120
skip-string-normalization = true
quiet = true
exclude = '''
/(
    \.git
)/
'''

[tool.isort]
profile = 'black'
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_third_party = ['any_case']
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
lines_after_imports = 2
atomic = true
combine_star = true
skip = []
